<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4345ce86-0669-48b7-9938-6a09017e2277</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="\ css-1wa3eu0-placeholder"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>